title: XRPL Validator
description: A description for your site
show_downloads: true
google_analytics: # (add your tracking ID if you want)

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
