title: XRPL Validator
description: This site hosts the `xrp-ledger.toml` file used for **XRP Ledger (XRPL) domain verification**, helping securely link this domain to its associated XRPL account.
show_downloads: true
google_analytics: "G-3DCL0Z21HY"

remote_theme: pages-themes/midnight@v0.2.0

include:
  - .well-known

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
