[[VALIDATORS]]
public_key = "nHUyiGRioLpta9x5AdQNPCuLCmYR5Ch3GuWsMLXEPWGJ7tKEuD1t"
description = "An XRPL Validator"
attestation = "A4A42FF34A292F882B3A80CE0D9C01D92A96FCE7D83D713AE85303F64BED4BA273AEF62F2658C25655693A74B1B9E87DC1E6EAB2F73BE2F60471C690072E9E07"
# Optional fields:
# network = "main"
owner_country = "US"  # Or your country code

[[ACCOUNTS]]
address = "rAW9kzFLg5ZDwfTLJu35AcNRf2TbTezJe"  # Must be a REAL, valid r... address
desc = "XRPLValidator"
