[[VALIDATORS]]
public_key = "nHUyiGRioLpta9x5AdQNPCuLCmYR5Ch3GuWsMLXEPWGJ7tKEuD1t"
description = "An XRPL Validator"
# Optional fields:
# network = "main"
owner_country = "US"  # Or your country code

[[ACCOUNTS]]
address = "rAW9kzFLg5ZDwfTLJu35AcNRf2TbTezJe"  # Must be a REAL, valid r... address
desc = "XRPLValidator"
